@baseurl = http://localhost:7071/api
###
GET {{baseurl}}/get-customer-by-id/douglas@teste.com/600537bf-bae7-4c5a-9d3e-01a5143c9e1e

###
GET {{baseurl}}/get-all-customers?email=joao@teste.com

###
GET {{baseurl}}/proposal/get-all

###
GET {{baseurl}}/proposal/get-by-id/029fa9f6-e2f3-4bf7-bd74-79793c5a1b24

###
POST {{baseurl}}/create-customer
Content-Type: application/json

{
    "name": "João Craici",
    "email": "joao@teste.com",
    "document":{
      "id":"123456",
      "name":"cpf"
    }
   
}
###
POST {{baseurl}}/proposal/create-proposal
Content-Type: application/json

{
        "customerFullName": "vitoria Souza",
        "customerEmail": "vitoria@teste.com",
        "customerTelephoneNumber": "1111111111",
        "serviceType": 3,
        "warrantyType": 1,
        "warrantyQtd": 2,
        "excecutionTime": 4,
        "power": "3,6",
        "zipCode": "13219110",
        "street": "Rua Nove de Julho",
        "neighborhood": "Centro",
        "city": "Jundiaí",
        "state": "SP",
        "products": [
          {
            "name": "ELETRODUTO 2",
            "quantity": 4
          },
          {
            "name": "CONDULETE 2",
            "quantity": 8
          }
        ],
        "totalPriceProducts": 1234,
        "labourValue": 54321,
        "totalPrice": 55555,
        "notes": "primeiro teste"
    },